name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Install Protobuf
        run: sudo apt-get install -y proto
      - name: Build AdMeta
        run: cargo build --release

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() && (github.event_name == 'push') && (github.ref == 'refs/heads/main') }}

    steps:
      - uses: actions/checkout@v2
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Docs
        # Add --all-features option when benchmark works
        run: |
          cargo doc --no-deps
          echo "<meta http-equiv=\"refresh\" content=\"0; URL=pallet_ad/index.html\"/>" > target/doc/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target/doc
